apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  labels:
    app: victoria
  name: victoria
spec:
  ports:
    - name: http
      port: 8428
      protocol: TCP
      targetPort: http
  selector:
    app: victoria